apiVersion: v1
kind: Service
metadata:
  name: {{ include "voidly-pay-hydra.fullname" . }}
  labels:
    {{- include "voidly-pay-hydra.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: agent-card
      protocol: TCP
      name: agent-card
  selector:
    {{- include "voidly-pay-hydra.selectorLabels" . | nindent 4 }}
